const MEDIA = [
  {
    artist: 'Emil Rottmayer',
    title: 'Descend',
    track: 'descend.mp3',
    src: 'descend.mp3',
    thumbnail: 'emilthumb.jpg',
    large: 'emilfull.jpg',
  },
  {
    artist: 'Artbat',
    title: 'Horizon',
    track: 'horizon.mp3',
    src: 'horizon.mp3',
    thumbnail: 'artbatthumb.png',
    large: 'artbatfull.png',
  },
  {
    artist: 'Vinai',
    title: 'Rise Up',
    track: 'riseup.mp3',
    src: 'riseup.mp3',
    thumbnail: 'vinaithumb.png',
    large: 'vinaifull.png',
  },
   {
    artist: 'Onra',
    title: 'Secretly',
    track: 'secretly.mp3',
    src: 'secretly.mp3',
    thumbnail: 'onrathumb.png',
    large: 'onrafull.png',
  },
  {
    artist: 'Burna Boy',
    title: 'On the Low',
    track: 'onthelow.mp3',
    src: 'onthelow.mp3',
    thumbnail: 'burnaboythumb.png',
    large: 'burnaboyfull.png',
  },
  {
    artist: 'YGPablo',
    title: 'AVM',
    track: 'avm.mp3',
    src: 'avm.mp3',
    thumbnail: 'ygpablothumb.png',
    large: 'ygpablofull.png',
  },
  {
    artist: 'Triplego',
    title: 'Game Over',
    track: 'gameover.mp3',
    src: 'gameover.mp3',
    thumbnail: 'triplegothumb.png',
    large: 'triplegofull.png',
  },
];

export default MEDIA;
