const MEDIA = [
  {
    artist: 'Emil Rottmayer',
    title: 'Descend',
    track: 'descend.mp3',
    src: 'media/descend.mp3',
    thumbnail: 'img/emilthumb.jpg',
    large: 'img/emilfull.jpg',
  },
  {
    artist: 'Artbat',
    title: 'Horizon',
    track: 'horizon.mp3',
    src: 'media/horizon.mp3',
    thumbnail: 'img/artbatthumb.png',
    large: 'img/artbatfull.png',
  },
  {
    artist: 'Vinai',
    title: 'Rise Up',
    track: 'rise-up.mp3',
    src: 'media/riseup.mp3',
    thumbnail: 'img/vinaithumb.png',
    large: 'img/vinaifull.png',
  },
   {
    artist: 'Onra',
    title: 'Secretly',
    track: 'secretly.mp3',
    src: 'media/secretly',
    thumbnail: 'img/onrathumb.png',
    large: 'img/onrafull.png',
  },
  {
    artist: 'Burna Boy',
    title: 'On the Low',
    track: 'on-the-low.mp3',
    src: 'media/onthelow.mp3',
    thumbnail: 'img/burnaboythumb.png',
    large: 'img/burnaboyfull.png',
  },
  {
    artist: 'YGPablo',
    title: 'AVM',
    track: 'ygpablo.mp3',
    src: 'media/avm.mp3',
    thumbnail: 'img/ygpablothumb.png',
    large: 'img/ygpablofull.png',
  },
  {
    artist: 'Triplego',
    title: 'Game Over',
    track: 'game-over.mp3',
    src: 'media/gameover.mp3',
    thumbnail: 'img/triplegothumb.png',
    large: 'img/triplegofull.png',
  },
];

export default MEDIA;
